-- This website no longer owns an operational database.
-- Menu management, store availability, orders, staff, reports, and payments are
-- handled by the Foundr1 OS backend. The site keeps only public pages plus
-- lightweight API proxies for menu, checkout, and order status.
